		CREATE TABLE ManCountry (
		  ManCountryID	tinyint NOT NULL IDENTITY(1,1),
		  ManCountryCode char(2)	NOT NULL,
		  ManCountryName varchar(30) NOT NULL,
		  CONSTRAINT PK_ManCountry_ManCountryID PRIMARY KEY CLUSTERED(ManCountryID))
		  SET IDENTITY_INSERT ManCountry ON
		  INSERT ManCountry (ManCountryID, ManCountryCode, ManCountryName)
		  VALUES 	(1, 'UK', 'United Kingdom')
					(2, 'DE', 'Deutschland')
					(3, 'SW', 'Sweden')
					(4, 'JP', 'Japan')
					(5, 'FR', 'France')
					(6, 'IT', 'Italy')
					(7, 'SP', 'Spain')
					(8, 'KR', 'Korea')
					(9, 'CZ', 'Czech Republic')
					(9, 'US', United States)
					(10, 'CH', 'China')
								 ALTER TABLE ManCountry ADD CONSTRAINT CHK_ManCountryOnylChar CHECK (ManCountryCode LIKE '[A-Z]%')
								  ALTER TABLE ManCountry ADD CONSTRAINT CHK_ManCountryCode2Char CHECK (LEN(ManCountryCode) = 2 )
		CREATE Table Manufacture  (
		  ManID tinyint NOT NULL IDENTITY(1,1),
		  ManName varchar(40) NOT NULL,
		  ManFullName varchar(50) NULL,
		  ManCountryID tinyint NOT NULL,
		  ManProfile varchar(60) NULL,
		  Description varchar(max) NULL,
		  Since smallint NULL,
		  CONSTRAINT PK_Manufacture_ManID PRIMARY KEY CLUSTERED(ManID),
		  CONSTRAINT FK_Manufacture_ManCountry_ManCountryID FOREIGN KEY (ManCountryID) REFERENCES ManCountry (ManCountryID))
		  INSERT Manufacture (ManID, ManName, ManFullName, ManCountryID, ManProfile, Description, Since)
		  VALUES 	(1, 'Acura', ' ' , 4, 'Luxury vehicle division of Japanese automaker' , ' ', 1986),
					(2, 'Alfa Romeo', 'Alfa Romeo Automobiles S.p.A', 6, 'Italian premium car manufacturer', ' ', 1910),
					(2, 'Aston Martin', 'Aston Martin Lagonda', 1, 'Luxury sports cars and grand tourers', ' ', 1910),
					(3, 'Audi', 'Audi AG', 2, 'Luxury Cars', 'Designs, engineers, produces, markets and distributes luxury vehicle', 1909),
					(4, 'BMW', 'Bayerische Motoren Werke AG', 2, 'Luxury vehicles and motorcycles', ' ', 1916),
					(5, 'Chevrolet', 'Chevrolet Motor Company', 9, 'Performance and incredible value for money', 'Chevrolet Division of General Motors Company', 1911),
					(6, 'Citroen', 'PSA Peugeot Citroen S.A.', 5, 'Passenger', ' ', 1919),
					(7, 'Daihatsu', 'Daihatsu Motor Co., Ltd', 4, 'Passenger and off-road vehicles', ' ', 1907),
					(8, 'Fiat', 'Fiat Automobiles S.p.A.', 6, 'Performance and luxury brand', 'Fiat Automobiles is the largest automobile manufacturer in Italy', 1899),
					(9, 'Ford', 'Ford Motor Company', 9, 'All rounder', ' ', 1916),
					(10, 'Honda', 'Honda Motor Company, Ltd.', 4, 'Passenger and Sport Cars', 'Manufacturer of automobiles, motorcycles, and power equipment', 1946),
					(11, 'Hyundai', 'Hyundai Motor Company', 8, 'Passenger Vehicles', 'Manufacture and distribution of motor vehicles and parts ', 1967,
					(12, 'Infiniti', ' ', 4, 'Luxury vehicle', 'Luxury vehicle division of Japanese automaker Nissan', 1989),
					(13, 'Kia', 'Kia Motors', 8, 'Passanger', 'Hyundai Motor Group ', 1944),
					(14, 'Lancia', 'Bayerische Motoren Werke AG', 6, 'Sport,Racing,Rally,Casula-Street', 'The brand is known for its strong rallying heritage ', 1906),
					(15, 'Jaguar', ' ', 1, 'Luxury&	Sport vehicles ', ' ', 1935),
					(16, 'Lamborghini', 'Automobili Lamborghini S.p.A.', 6, 'Luxury& Sport vehicles', ' ', 1963),
					(17, 'Lexus', ' ', 4, 'Luxury vehicles', 'luxury vehicle division of the Japanese automaker Toyota', 1989),
					(18, 'Mazda', 'Mazda Motor Corporation', 4, 'Passanger and Sport', ' ', 1920),
					(19, 'Mercedes', 'Mercedes-Benz AG', 2, 'Luxury vehicles', ' ', 1926),
					(20, 'Mini', ' ', 1, 'Small Cars', 'Owned by German automotive company BMW since 2000', 1959),
					(21, 'Mitsubishi', 'Mitsubishi Group', 4, 'Passanger and sport', 'Japanese multinational companies in a variety of industries',1870),
					(22, 'Nissan', 'Nissan Motor Company, Ltd', 4,  'Passanger and sport', 'Japanese multinational automobile manufacturer', 1933),
					(23, 'Opel', 'Opel Automobile GmbH', 2, 'popular cars that were available to the common man', 'It was owned by General Motors', 1862),
					(24, 'Peugeot', ' ', 5,	'French mainstream car brand', 'A sharp design for Allure, Instinctive driving experience for Emotion', 1810),
					(25, 'Porsche', 'Porsche AG', 2, 'Sports Cars', ' ', 1931),
					(26, 'Renault', 'Renault S.A.', 5, 'Passenger cars, light commercial vehicles', 'The company produces a range of cars and vans, and in the past has manufactured trucks, tractors, tanks, buses/coaches, aircraft and aircraft engines, and autorail vehicles.', 1899),
					(27, 'Rover', 'The Rover Company Limited', 1, 'Passanger', ' ', 1878),
					(28, 'Saab', 'Saab Automobile AB', 3, 'Luxury Well Enginered Cars', 'began a project to design a small automobile', 1945),
					(29, 'Seat', 'SEAT, S.A.', 7, 'Passenger and Sport Cars', 'Volkswagen AG took over the full ownership of SEAT', 1950),
					(30, 'Smart', 'divison of Daimler AG', 2, 'Small Cars', ' ', 1944),
					(31, 'Skoda', 'Škoda Auto', 9, 'Passenger Cars', 'Škoda was bought by the Volkswagen Group in 2000', 1895),
					(32, 'Subaru', 'Subaru Corporation', 4, 'Passenger, Tour, Sport, Rally cars', 'automobile manufacturing division of Japanese transportation conglomerate', 1953),
					(33, 'Suzuki', 'Suzuki Motor Corporation', 4, 'All Rounder', 'Suzuki manufactures automobiles, four-wheel drive vehicles, motorcycles, all-terrain vehicles (ATVs), outboard marine engines, wheelchairs and a variety of other small internal combustion engines', 1909),
					(34, 'Tesla', 'Tesla, Inc.', 9, 'Electric vehicles', ' ', 2003),
					(35, 'Toyota', 'Toyota Motor Corporation', 4, 'All Rounder', 'Toyota is one of the largest automobile manufacturers in the world, based on sales which include its subsidiaries', 1937),
					(36, 'Volkswagen', 'Volkswagen AG', 2, 'All Rounder', 'The Volkswagen Group sells passenger cars under the Audi, Bentley, Bugatti, Lamborghini, Porsche, SEAT, Škoda and Volkswagen', 1937),
					(37, 'Volvo', 'Volvo Cars', 3, 'Swedish luxury automobile marque', ' ', 1927),
					(38, 'Ferrari', 'Ferrari S.p.A.', 6, 'luxury sports car', 'Owned by Fiat Chrysler Automobiles since 2014', 1939)
			
		CREATE Table CarCategoryType (
			CarCategoryTypeID smallint NOT NULL IDENTITY(1,1),
			CategoryName varchar(20) NOT NULL,
			CONSTRAINT PK_CarCategoryType_CarCategoryID PRIMARY KEY CLUSTERED(CarCategoryTypeID),)
			INSERT CarCategoryType (CategoryName)
			VALUES 	('Hatchback'),
					('Sedan'),
					('SUV'),
					('Crossover'),
					('MiniVan'),
					('Limousine'),
					('Grand Tourer'),
					('Coupe'),
					('SportCompact'),
					('SuperSport'),
					('Rally'),
					('Luxury'),
					('VAN'),
					('Convertible')
					
		CREATE Table CarModel (
		  CarModelID int NOT NULL IDENTITY(1,1),
		  ManID tinyint NOT NULL,
		  Modelname varchar(30) NOT NULL,
		  CarCategoryTypeID smallint NULL
		  CONSTRAINT PK_CarModel_CarModelID PRIMARY KEY CLUSTERED(CarModelID),
		  CONSTRAINT FK_CarCategoryType_CarModel_CarCategoryTypeID FOREIGN KEY (CarCategoryTypeID) REFERENCES CarCategoryType (CarCategoryTypeID)
		  CONSTRAINT FK_Manufacture_Carmodel_ManID FOREIGN KEY (ManID) REFERENCES Manufacture (ManID))
		  
		INSERT CarModel(ManID, ModelName, CarCategoryTypeID)
		VALUES
				( 3, 'DB9', 12),
				( 3, 'DBS', 12),
				( 3, 'Rapide', 12),
				( 3, 'V12 Vantage',12),
				( 3, 'V8 Vantage S',12),
				( 3, 'V8 Vantage',12),
				( 3, 'Vantage',12 ),
				( 3, 'Vantage',12 ),
				( 3, 'Virage',12 ),
				( 4, 'A3',1 ),
				( 4, 'A4',2 ),
				( 4, 'A5',2 ),
				( 4, 'A6',6 ),
				( 4, 'A7',12 ),
				( 4, 'A8',6 ),
				( 4, 'Q5',3 ),
				( 4, 'Q7',3 ),
				( 4, 'S4',9 ),
				( 4, 'S5',9 ),
				( 4, 'S6',9 ),
				( 4, 'S8',9 ),
				( 5, 'M3',9 ),
				( 5, 'M5',9 ),
				( 5, 'M6',9 ),
				( 5, 'X3',3 ),
				( 5, 'X5 M',3 ),
				( 5, 'X5',3 ),
				( 5, 'X6 M',3 ),
				( 5, 'X6',3 ),
				( 5, 'Z4 M Roadster',10 ),
				( 5, 'Z4 M',10 ),
				( 5, 'Z4',12 ),
				( 7, 'C2',8 ),
				( 7, 'C3',8 ),
				( 7, 'C3 Picasso',5 ),
				( 7, 'C4',2 ),
				( 7, 'C4 Grand',7 ),
				( 7, 'C4 Cactus',4 ),
				( 7, 'C4 Picasso',7 ),
				( 7, 'Jumper',13 ),
				( 7, 'C5', 2),
				( 7, 'C6', 2),
				( 6, 'Avalanche',2 ),
				( 6, 'Aveo',2 ),
				( 6, 'Camaro',2 ),
				( 6, 'Cobalt', 2),
				( 6, 'Colorado',2 ),
				( 6, 'Corvette', 10),
				( 6, 'Cruze',2 ),
				( 6, 'Equinox',2 ),
				( 6, 'Impala', 2),
				( 39, '430 Scuderia',10),
				( 39, '430 Scuderia',10 ),
				( 39, '458 Italia',10 ),
				( 39, '599 GTB Fiorano',10 ),
				( 39, '612 Scaglietti',10 ),
				( 39, 'California',10 ),
				( 39, 'F430',10 ),
				( 39, 'FF',10 ),
				( 9, '500',1 ),
				( 9, '500L',5 ),
				( 9, '500X',4 ), 
				( 9, 'Punto',1 ),
				( 9, 'Panda',1 ),
				( 9, 'Tipo',8 ),
				( 10, 'C-MAX Hybrid',5 ),
				( 10, 'Crown Victoria', 2),
				( 10, 'E150',3 ),
				( 10, 'E250',3 ),
				( 10, 'E350',3 ),
				( 10, 'Edge',3 ),
				( 10, 'Escape',3 ),
				( 10, 'E-Series',3 ),
				( 10, 'Expedition EL', 3),
				( 10, 'Expedition', 3),
				( 10, 'Explorer Sport Trac',3 ),
				( 10, 'Explorer',3 ),
				( 10, 'F150',3 ),
				( 10, 'F250',3 ),
				( 10, 'F350',3 ),
				( 10, 'F450',3 ),
				( 10, 'Fiesta',1 ),
				( 10, 'Focus ST',9 ),
				( 10, 'Focus',1 ),
				( 10, 'F-Series Super Duty',3 ),
				( 10, 'F-Series',3 ),
				( 10, 'Fusion',5 ),
				( 10, 'GT500',10 ),
				( 10, 'Mustang',10 ),
				( 10, 'Ranger',3 ),
				( 10, 'Transit Connect',13 ),
				( 11, 'Accord Crosstour',7 ),
				( 11, 'Accord',2 ),
				( 11, 'Civic',1 ),
				( 11, 'Civic',2 ),
				( 11, 'Crosstour',7 ),
				( 11, 'CR-V',3 ),
				( 11, 'CR-Z',9 ),
				( 11, 'Insight',8 ),
				( 11, 'S2000',9 ),
				( 12, 'Accent',2 ),
				( 12, 'Azera',2 ),
				( 12, 'Elantra',2 ),
				( 12, 'Entourage',2 ),
				( 12, 'Equus',2 ),
				( 12, 'Genesis Coupe',8 ),
				( 12, 'Genesis', 2),
				( 12, 'Santa Fe',3 ),
				( 12, 'Sonata',3 ),
				( 12, 'Tucson',3 ),
				( 12, 'Veloster',1 ),
				( 12, 'Veracruz',NULL ),
				( 13, 'EX',NULL ),
				( 13, 'FX',NULL ),
				( 13, 'G',NULL ),
				( 13, 'G25', 2),
				( 13, 'G37', 2),
				( 13, 'IPL G',NULL ),
				( 13, 'M',NULL ),
				( 13, 'QX',3 ),
				( 13, 'QX56',3 ),
				( 16, 'XJ',10 ),
				( 16, 'XK',10 ),
				( 14, 'Amanti', 1),
				( 14, 'Borrego',2 ),
				( 14, 'Carens',1 ),
				( 14, 'Forte',2 ),
				( 14, 'Optima',2 ),
				( 14, 'Rio',1 ),
				( 14, 'Rondo',2 ),
				( 14, 'Sedona',2 ),
				( 14, 'Sorento',3 ),
				( 14, 'Soul',1 ),
				( 14, 'Spectra',2 ),
				( 14, 'Sportage',3 ),
				( 17, 'Aventador',10 ),
				( 17, 'Gallardo',10 ),
				( 17, 'Murcialago',10 ),
				( 18, 'CT', 1),
				( 18, 'ES',12 ),
				( 18, 'GS',2 ),
				( 18, 'GX',2 ),
				( 18, 'HS',2 ),
				( 18, 'IS F',2 ),
				( 18, 'IS',2 ),
				( 18, 'IS-F',2 ),
				( 18, 'LFA',2 ),
				( 18, 'LS Hybrid',12 ),
				( 18, 'LS',12 ),
				( 18, 'LX',12 ),
				( 18, 'RX Hybrid',12 ),
				( 18, 'RX',12 ),
				( 18, 'SC',12 ),
				( 19, 'CX-5',4 ),
				( 19, 'CX-7',3 ),
				( 19, 'CX-9',3 ),
				( 19, 'Mazda2',1 ),
				( 19, 'Mazda5',2 ),
				( 19, 'Mazda6',2 ),
				( 19, 'Mazdaspeed 3',1 ),
				( 19, 'Miata MX-5',10 ),
				( 19, 'MX-5',10 ),
				( 20, 'CL65 AMG',10 ),
				( 20, 'CL-Class',10 ),
				( 20, 'CLS-Class',10 ),
				( 20, 'E-Class',2 ),
				( 20, 'G-Class',3 ),
				( 20, 'GL-Class',3 ),
				( 20, 'GLK-Class',3 ),
				( 20, 'M-Class',9 ),
				( 20, 'R-Class',10 ),
				( 20, 'S-Class',10 ),
				( 20, 'SL-Class',10 ),
				( 20, 'SLK55 AMG',10 ),
				( 20, 'SLK-Class',10 ),
				( 20, 'SLS AMG',10 ),
				( 20, 'SLS-Class',10 ),
				( 20, 'Sprinter 2500',13 ),
				( 20, 'Sprinter 3500',13 ),
				( 20, 'Sprinter',13 ),
				( 21, 'Clubman',1 ),
				( 21, 'Cooper Clubman',9 ),
				( 21, 'Cooper Countryman',9 ),
				( 21, 'Cooper',1 ),
				( 21, 'Countryman',1 ),
				( 22, 'Eclipse',2 ),
				( 22, 'Endeavor',2 ),
				( 22, 'Galant',2 ),
				( 22, 'i-MiEV',2 ),
				( 22, 'Lancer Evolution',2 ),
				( 22, 'Lancer', NULL),
				( 22, 'Outlander Sport',NULL ),
				( 22, 'Outlander',3 ),
				( 22, 'Raider',3 ),
				( 23, '350Z',9 ),
				( 23, 'Altima',2 ),
				( 23, 'Armada',3 ),
				( 23, 'Cube',1 ),
				( 23, 'Frontier',3 ),
				( 23, 'GT-R',10 ),
				( 23, 'JUKE',4 ),
				( 23, 'Leaf',1 ),
				( 23, 'Murano',4 ),
				( 23, 'Pathfinder',3 ),
				( 23, 'Rogue',3 ),
				( 23, 'Sentra',4 ),
				( 23, 'Titan',3 ),
				( 23, 'Versa',3 ),
				( 23, 'Xterra',3 ),
				( 26, '911',10 ),
				( 26, 'Boxster',10 ),
				( 26, 'Cayenne',10 ),
				( 26, 'Cayman',10 ),
				( 26, 'Panamera',10 ),
				( 27, 'Clio',1 ),
				( 27, 'Megane',1 ),
				( 27, 'Espace',5 ),
				( 27, 'Scenic',1 ),
				( 27, 'Captur',4 ),
				( 27, 'Kadjar',4 ),
				( 27, 'Twingo',1 ),
				( 27, 'Kangoo',5 ),
				( 27, 'Master',13 ),
				( 27, 'Trafic',13 ),
				( 29, '9-3',2 ),
				( 29, '9-4X',2 ),
				( 29, '9-5', 2),
				( 29, '9-7X',2 ),
				( 31, 'Fortwo',1 ),
				( 33, 'BRZ',10 ),
				( 33, 'Forester',2 ),
				( 33, 'Impreza WRX',11 ),
				( 33, 'Impreza',2 ),
				( 33, 'Legacy',2 ),
				( 33, 'Outback',4 ),
				( 34, 'Equator',4 ),
				( 34, 'Grand Vitara',3 ),
				( 34, 'Kizashi',1 ),
				( 34, 'SX4',4 ),
				( 35, 'Roadster',9 ),
				( 35, 'Model S',8 ),
				( 36, '4Runner',NULL ),
				( 36, 'Avalon',NULL ),
				( 36, 'Camry Hybrid',2 ),
				( 36, 'Camry',2 ),
				( 36, 'Corolla',1 ),
				( 36, 'Corolla',2 ),
				( 36, 'FJ Cruiser',3 ),
				( 36, 'Highlander',3 ),
				( 36, 'Land Cruiser',3 ),
				( 36, 'Prius c',1 ),
				( 36, 'Prius Plug-in Hybrid',1 ),
				( 36, 'Prius Plug-in',1 ),
				( 36, 'RAV4',3 ),
				( 36, 'Sequoia',4 ),
				( 36, 'Sienna',1 ),
				( 36, 'Tacoma',2 ),
				( 36, 'Tundra', 3),
				( 36, 'TundraMax', 1),
				( 36, 'Venza',1 ),
				( 36, 'Yaris',1 ),
				( 24, 'Corsa',1 ),
				( 24, 'Insignia',2 ),
				( 24, 'Astra',1 ),
				( 24, 'Mokka',4 ),
				( 37, 'CC',8 ),
				( 37, 'Eos',8 ),
				( 37, 'GLI',1 ),
				( 37, 'Golf',1 ),
				( 37, 'GTI',9 ),
				( 37, 'Jetta',2 ),
				( 37, 'New Beetle',1 ),
				( 37, 'Passat',2 ),
				( 37, 'R32',9 ),
				( 37, 'Rabbit',1 ),
				( 37, 'Routan',2 ),
				( 37, 'Tiguan',4 ),
				( 37, 'Touareg',3 ),
				( 38, 'C30',1 ),
				( 38, 'C70',1 ),
				( 38, 'S40',2 ),
				( 38, 'S60',2 ),
				( 38, 'S80', 2),
				( 38, 'V50', 2),
				( 38, 'V70',2 ),
				( 38, 'XC60',4 ),
				( 38, 'XC70',3 ),
				( 38, 'XC90',3 ),
				( 30, 'Ibiza',1),
				( 30, 'Leon', 1),
				( 30, 'CupraR',9 ),
				( 25, '108',1 ),
				( 25, '208', 1),
				( 25, '308',1 ),
				( 25, '508',2 ),
				( 25, '2008',4 ),
				( 25, '3008',4 ),
				( 25, '5008',3 ),
				( 32, 'RS Octavia',2 ),
				( 32, 'Octavia', 2),
				( 32, 'SuperB',2 ),
				( 32, 'Karoq',3 )
				
		CREATE Table CarFeature (
		  CarFeatureID tinyint NOT NULL IDENTITY(1,1),
		  FeatureName varchar(40) NOT NULL,
		  CONSTRAINT PK_CarFeature_CarFeatureID PRIMARY KEY CLUSTERED(CarFeatureID))
		INSERT CarFeature(FeatureName)
		VALUES 	('Power Steering'),
				('Rain sensors and light'),
				('Headlight washers'),
				('Electric rear windows'),
				('Electrically folding rear view mirrors'),
				('Height adjustment dirver seat'),
				('Climate Control'),
				('Heated windshield'),
				('Heated side mirrors'),
				('Heated front seats'),
				('Cooled glove box'),
				('ON board Computer'),
				('Audio contoller on the steering wheel'),
				('6 speakers'),
				('Support USB'),
				('Support Bluetooth'),
				('Central lock on  the remote control'),
				('Immobilizer'),
				('Reverse Parking Sensors'),
				('Reverse Parking Camera'),
				('Speed Warning System'),
				('City Sensitive Braking System'),
				('Navigational System')
				
				
		CREATE Table ProductCarFeature (
		 CarID int NOT NULL,
		 CarFeatureID tinyint NOT NULL,
		 CONSTRAINT FK_ProductCarFeature_CarForsSale_CarID FOREIGN KEY (CarID) REFERENCES CarForSale (CarID) ON DELETE CASCADE,
		 CONSTRAINT FK_ProductCarFeature_CarFeature_CarFeatureID FOREIGN KEY (CarFeatureID) REFERENCES  CarFeature (CarFeatureID))
		 BULK INSERT ProductCarFeature FROM 'C:\Users\flint\Desktop\CarModelFeatures.csv' WITH 
		(FIELDTERMINATOR =';', ROWTERMINATOR = '\n', CODEPAGE = 'ACP')

	
		CREATE Table CarEngineFuel (
			CarEngineFuelID tinyint NOT NULL IDENTITY(1,1),
			CarEngineName varchar(10) NOT NULL,
			CONSTRAINT PK_CarEngineFuel_CarEngineFuelID PRIMARY KEY CLUSTERED(CarEngineFuelID))
			INSERT CarEngineFuel (CarEngineName)
			VALUES 	('Petrol'),
					('Diesel'),
					('Hybrid'),
					('Electirc'),
					('LPG')
					
		CREATE Table CarForSale (
		  CarID int NOT NULL IDENTITY(1,1),
		  CarModelID int NOT NULL,
		  Description varchar(max) NULL,
		  CarColor varchar(15) NULL,
		  ListPrice money NOT NULL,
		  CostPrice money NULL,
		  LunchYear smallint NULL,
		  CarEngineFuelID tinyint NOT NULL,
		  CarKM int NULL,
		  PremiseCode tinyint NOT NULL,
		  CarPlateNO varchar(10) NULL,
		  DataCreate date NOT NULL CONSTRAINT CHK_CarForSale_DataCreate_AtNow CHECK (DataCreate <= SYSDATETIME())
		CONSTRAINT DF_CarForSale_DataCreate DEFAULT (SYSDATETIME()),
		  DataUpdate date NULL,
		CONSTRAINT PK_CarForSale_CarID PRIMARY KEY CLUSTERED(CarID),
		CONSTRAINT FK_CarForSale_CarEngineFuel_CarEngineFuelID FOREIGN KEY (CarEngineFuelID) REFERENCES  CarEngineFuel (CarEngineFuelID),
		CONSTRAINT FK_CarForSale_Premise_PremiseCode FOREIGN KEY (PremiseCode) REFERENCES  Premise (PremiseCode),
		CONSTRAINT FK_CarForSale_CarModel_CarModelID FOREIGN KEY (CarModelID) REFERENCES  CarModel (CarModelID))
		
		
		CREATE Table Premise (
			 PremiseCode tinyint NOT NULL IDENTITY(1,1),
			 Country varchar(20) NOT NULL,
			 City varchar(20) NOT NULL,
			 Address varchar(30) NULL,
			 PhoneNumber varchar(20) NOT NULL,
			 PostcalCode varchar(20) NULL,
			 CONSTRAINT PK_Premise_PremiseCode PRIMARY KEY CLUSTERED(PremiseCode))
			INSERT Premise (Country, City, Address, PhoneNumber, PostcalCode)
			VALUES 	('Hungary', 'Budapest', 'Kosztolányi Dezső út 27', '0612344325', '1222'),
					('Hungary', 'Misckolc', 'Tárógató sugárút 127', '0645564013', '3524'),
					('Hungary', 'Mosonmagyaróvár', 'Alkotmány út 65', '0696784567', '9200'),
					('Hungary', 'Pécs', 'Ali baba út 1', '0672111983', '7600'),
					('Hungary', 'Szeged', 'London  sugárút 88', '0662334331', '6700')
				
		CREATE Table Employee	(
			EmployeeID smallint IDENTITY(1,1),
			FirstName varchar(20) NOT NULL,
			LastName varchar(20) NOT NULL,
			Email varchar(30) NULL,
			PremiseCode tinyint NULL,
			Jobtitle varchar(20) NOT NULL,
			Address varchar(50) NULL,
			PhoneNumber varchar(20) NOT NULL,
			TaxNum varchar(20) NULL,
				CONSTRAINT PK_Employee_EmployeeID PRIMARY KEY CLUSTERED(EmployeeID))
			INSERT Employee (LastName, FirstName, Email, PremiseCode, Jobtitle, Address, PhoneNumber, TaxNum)
			VALUES 	('Kiss', 'Béla', 'belakiss@gmail.com', 1, 'SalesPerson', '1112 Budapest Kútvölgyi út 23', '06304567891', '2465869710'),
					('Dimitrj', 'Júlia', 'dimitijj@gmail.com', 1, 'PremiseManager', '1023, Fillér utca 156', '06304567890', '8465877910'),
					('Borsos', 'Áron', 'trulyxpensive@gmail.com', 3, 'PremiseManager', '9200 Mosonmagyaróvár Alkony utca 4', '06304567892', '3564817910'),
					('Mikorka', 'Kálmán', 'mikorkakalman@gmail.com', 2, 'SalesPerson', '3524 Miskolc Győri kapu 24', '06304567893', '4562587931'),
					('Mangal', 'Ica', 'piggycus@gmail.com', 1, 'SalesPerson', '1201 Kossuth Lajos utca 125','06304567894', '584123795'),
					('Nagy', 'Géza', 'gezabig@gmail.com', 2, 'SalesPerson', '3524 Miskolc Diósgyóri út 12','06304567895', '4796325448'),
					('Sánta', 'Ferenc', 'gimpyfrank@gmail.com', 2, 'PremiseManager', '3525 Miskolc Kilátó kanyar 4' ,'06304567896', '96322587456'),
					('Gábor', 'András', 'gaborandris@gmail.com', 3, 'SalesPerson', '9200 Mosonmagyaróvár Bécsi űt 4','06304567897', '5497862144'),
					('Falc', 'Jenő', 'flacjenci@gmail.com', 3, 'SalesPerson', '9200 Mosonmagyaróvár Soproni űt 34','06304567898', '7632180642'),
					('Sándor', 'Benedek', 'benedeksandor@gmail.com', 4, 'PremiseManager', '7600 Pécs Minaret sétány 3','06304567899', '2154789633'),
					('Barcsi', 'Laura', 'barcsilau@gmail.com', 4, 'SalesPerson', '7600 Pécs Sümegi út 14','06304567810', '8521147891'),
					('Hekk', 'Elek', 'mr.hoax@gmail.com',' ', 'IT SOLUTIONS', '9999 Smwhr@basment', '063099909999', '9987999879'),
					('Búgó', 'Brigitta', 'bugobriggite@gmail.com', 4, 'SalesPerson', '7600 Pécs Kozári út 17','06304567811', '4522114891'),
					('Fancsal', 'Dóra', 'dorifancsal@gmail.com', 5, 'PremiseManager', '6700 Szeged Hódmezővásárhelyi út 114','06304567812', '1478523698'),
					('Sipos', 'Mikháel', 'sipmik@gmail.com', 5, 'SalesPerson', '6700 Szeged Újszegedi út 54','06304567813', '7345712394'),
					('Tánczos', 'Ábel', 'dancerabby@gmail.com', 5, 'SalesPerson', '6700 Szeged Mártély sétány 8', '06304567814', '1327984562'),
					('Deal', 'Elek', 'elekarethewholesales@gmail.com', ' ', 'WholeSalesManager', '1023 Panoráma út 55','063044444449', '7981567345')
			
		CREATE TABLE Purchase (
		PaymentNO int NOT NULL IDENTITY(1,1),
		CarID int NOT NULL,
		CustomerID int NOT NULL,
		UnitPrice money NOT NULL,
		EmployeeID smallint NOT NULL,
		PurchaseDate datetime NOT NULL CONSTRAINT DF_Purchase_PurchaseDate DEFAULT (SYSDATETIME()),
		PaymentTypeID tinyint NOT NULL CONSTRAINT DF_DailyPayment2_PaymentTypeID DEFAULT '1',
		DiscontValue decimal NULL,
		DiscountedPrice Computed
		CONSTRAINT PK_Purchase_PaymentNO PRIMARY KEY CLUSTERED (PaymentNO),
		CONSTRAINT FK_Purchase_Customer_CustomerID FOREIGN KEY (CustomerID) REFERENCES  Customer (CustomerID) ,
		CONSTRAINT FK_Purchase_PaymentType_PaymentTypeID FOREIGN KEY (PaymentTypeID) REFERENCES  PaymentType (PaymentTypeID),
		CONSTRAINT FK_Purchase_Discount_DiscountID FOREIGN KEY (DiscountID) REFERENCES Discount (DiscountID) ,
		CONSTRAINT FK_Purchase_Employee_EmployeeID FOREIGN KEY (EmployeeID) REFERENCES Employee (EmployeeID) ,
		CONSTRAINT CHK_Purchase_PaymentTypeID_Range1To2 CHECK (PaymentTypeID BETWEEN 1 AND 2),
		CONSTRAINT CHK_Purchase_Purchase_NotFuture CHECK (PurchaseDate <= SYSDATETIME()))

		BULK INSERT Purchase FROM 'C:\Users\flint\Desktop\Purchase.csv' WITH 
		(FIELDTERMINATOR =';', ROWTERMINATOR = '\n', CODEPAGE = 'ACP' ,FIRSTROW = 2)


		CREATE Table Customer (
		  CustomerID int NOT NULL IDENTITY(1,1),
		  FirstName varchar(30) NOT NULL,
		  LastName varchar(30) NOT NULL,
		  PhoneNumber varchar(11) NOT NULL,
		  City varchar(30) NOT NULL,
		  AdressLine1 varchar(40) NULL,
		  TaxNum nvarchar(21) NULL,
		  CONSTRAINT PK_Customer_CustomerID PRIMARY KEY CLUSTERED(CustomerID),
		  CONSTRAINT CHK_Customer_PhoneNumber_Number CHECK (LEN(PhoneNumber) IN (10))
		)
		SET IDENTITY_INSERT dbo.customer OFF
		INSERT Customer (FirstName,LastName,PhoneNumber ,City,AdressLine1,TaxNum)
		VALUES ('Tordai','Zsana','3045756781','Budapest','Kiss János utca 54','7898953546')
		BULK INSERT Customer FROM 'C:\Users\flint\Desktop\Customer02.csv' WITH 
		(FIELDTERMINATOR =';', ROWTERMINATOR = '\n', CODEPAGE = 'ACP')

	CREATE Table DictUserLogin (
	  UserID smallint NOT NULL IDENTITY(1,1),
	  UserName varchar(30) NOT NULL,
	  UserLogin varchar(30) NOT NULL,
	  AdminRole bit NOT NULL,
	  EmpRole bit NOT NULL,
	  ManagerRole bit NOT NULL,
	  WebAPProle bit NOT NULL,
	  IsActive bit NOT NULL,
	)
	INSERT DictUserLogin (UserName, UserLogin, AdminRole,EmpRole, ManagerRole, WebAPProle, IsActive)
					VALUES	('Admin Kalmán', 'Zsadmin', 1, 0, 0, 1, 0),
							('Fancsal Dóra', 'FancsaLee',0,0,1,0,1),
							('Borsos Áron', 'XpnSV',0,0,1,0,1),
							('Webapp', 'WebAPP',0,0,0,1,1),
							('Falc Jenő', 'FalcLee',0,0,1,0,1),
							('View Béla', 'Employ',0,1,0,0,1)

		CREATE Table PaymentType (
			PaymentTypeID tinyint NOT NULL IDENTITY(1,1),
			TypeName varchar(10) NOT NULL,
			CONSTRAINT PK_PaymentType_PaymentTypeID PRIMARY KEY CLUSTERED(PaymentTypeID),
			CONSTRAINT DF_PaymentType_PaymentTypeID DEFAULT (1),)
		INSERT PaymentType (TypeName)
		VALUES 	('CASH')
					('CreditCard')
		
		
		CREATE TABLE ProductLog (
			ProductLogID int IDENTITY PRIMARY KEY,
			CarID int,
			DMLAction varchar(10),
			OldListPrice money,
			NewListPrice money,
			InsertUser varchar(100) DEFAULT SUSER_SNAME(),
			InsertDate datetime2 DEFAULT SYSDATETIME())
				
CREATE UNIQUE NONCLUSTERED INDEX AK_Employee_TaxNum ON dbo.Employee (TaxNum)
CREATE UNIQUE NONCLUSTERED INDEX AK_CarForSale_CarPlateNo ON dbo.CarForSale (CarPlateNo)
CREATE UNIQUE NONCLUSTERED INDEX AK_Customer_TaxNum ON dbo.Customer (TaxNum)
CREATE NONCLUSTERED INDEX IX_Customer_LastName ON dbo.Customer (LastName)